# Created using wingetcreate 1.9.3.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.9.0.schema.json

PackageIdentifier: GuraNotFound.Ninarium
PackageVersion: 132.0.6834.83
InstallerType: exe
UpgradeBehavior: install
Protocols:
- http
- https
- mailto
- tel
FileExtensions:
- htm
- html
- pdf
- shtml
- svg
- webp
- xht
- xhtml
Installers:
- Architecture: x64
  Scope: user
  InstallerUrl: https://github.com/guranotfound/Ninarium/releases/download/132.0.6834.83/mini_installer_sync.exe
  InstallerSha256: FEC9AA740BA7C9FAA1BB8EB64404EC066DB68372A8FB8D58694C2CF779DAEC76
  InstallerSwitches:
    Silent: "--silent --do-not-launch-chrome"
    SilentWithProgress: "--silentWithProgress --do-not-launch-chrome"
- Architecture: x64
  Scope: machine
  InstallerUrl: https://github.com/guranotfound/Ninarium/releases/download/132.0.6834.83/mini_installer_sync.exe
  InstallerSha256: FEC9AA740BA7C9FAA1BB8EB64404EC066DB68372A8FB8D58694C2CF779DAEC76
  InstallerSwitches:
    Silent: "--silent --do-not-launch-chrome"
    SilentWithProgress: "--silentWithProgress --do-not-launch-chrome"
    Custom: "--system-level"
ManifestType: installer
ManifestVersion: 1.9.0
ReleaseDate: 2025-01-18

